name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip3 install poetry
          make install
      - name: Run linter and pytest
        run: |
          make check
      - name: Test & publish code coverage
        uses: ./.github/actions/cc-test-reporter
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: e27daf98a59780b907ca8997a8466f3d6dc5fa3c287c865a8037daa2d6b021b0
        with:
          coverageCommand: make test-coverage
          debug: true

